### ISSUE TITLE
README installation info

### ISSUE THREAD

**Issue by MichaelMedford** [jluastro/PopSyCLE#23]
Currently the README states
```
**Installation**
PopSyCLE can be installed as a standard python package.
```

I'm not sure that as a user I would know what that means. I think of a "standard" installation as through a package managers such as pip or conda, which we do not currently support. I think this needs to be changed to something like:

```
**Installation**
To install PopSyCLE, clone the GitHub repository and 
add the repository's path to your `PYTHONPATH`. 
For example:

git clone git@github.com:jluastro/PopSyCLE.git
echo "export PYTHONPATH=$PWD/PopSyCLE:$PYTHONPATH" >> ~/.bashrc
```

What do you think?

**Comment by caseylam** [comment]
Yes, that sounds like a good clarification. Can you make the change?

**Comment by MichaelMedford** [comment]
done
