### ISSUE TITLE
Astrometric Microlensing Signals

### ISSUE THREAD

**Issue by avalluvan** [jluastro/PopSyCLE#41]
Hello, I have been using PopSyCLE as part of my undergraduate thesis work. I was trying to figure out where the astrometric microlensing parts were incorporated and I managed to find definitions for functions such as calc_delta_c() in popsycle.synthetic and a couple of other function definitions in popsycle.utils. However, none of these seem to be invoked anywhere in the code. Does the default structure of PopSyCLE not employ astrometric microlensing to refine candidate microlensing events?

**Comment by caseylam** [comment]
Hi @aravindbharathi sorry for the late reply, I missed the notification for this so just seeing now... I am not sure if this reply is too late to be useful, but just in case it is (and for future reference):

You are right, astrometric microlensing is not used in the step to refine the candidate microlensing events-- all it does is check that the source is not dark, check the closest approach happens within the survey window, and calculates a bunch of observable quantities associated with the event.

However, one of the parameters returned in the Einstein radius-- from this, you can calculate what the maximum astrometric shift is for the event.
