### ISSUE TITLE
Document Development Process

### ISSUE THREAD

**Issue by jluastro** [jluastro/PopSyCLE#5]
Add to README a link to a Develop on PopSyCLE and then add some notes about our general procedure. We agreed to:

use branches (not forks)
when ready to merge your branch with master, submit a pull request
get some kind of sign off from a subset of people and then have someone (Jessica or Casey) accept the pull request.

**Comment by MichaelMedford** [comment]
I have added a PopSyCLE development guide to the `docs` folder, and included a link to it in the README.
