### ISSUE TITLE
docstring of `refine_events()`

### ISSUE THREAD

**Issue by rpoleski** [jluastro/PopSyCLE#61]
The `input_root` defines root for 5 files (see lines 4154-4166) whereas docstring informs only about 2 (lines 4082-4084). In my case, this caused an error when I tried to use a single output from `run_galaxia()` in multiple runs of `perform_pop_syn()` and further steps from the manual. The solution that worked was to copy `_galaxia_params.txt` file.

**Comment by nsabrams** [comment]
I added these three additional files to the refine_events docstring on the dev branch. Either copying that file or making a symbolic link to it should work.
